# -*- coding: utf-8 -*-
"""Mental_Health_Support_Bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LYJzEFdUgGkDxrb8bFUtaLXZLCt3dI8u

# Library
"""

import random
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer

# Download necessary NLTK resources
nltk.download("vader_lexicon")

# Initialize sentiment analyzer
sia = SentimentIntensityAnalyzer()

"""# Response Library"""

RESPONSE_LIBRARY = {
    "greeting": [
        "Hello! How are you feeling today?",
        "Hi there! I’m here to listen. How can I support you today?",
        "Welcome! I’m here to help. What’s on your mind?",
    ],
    "stress": [
        "It sounds like you’re feeling stressed. Would you like a self-care tip, or to talk more about it?",
        "Stress can be overwhelming. Let’s talk about it, or I can suggest ways to manage it.",
        "Feeling stressed is natural. Do you want to share more about what’s causing it, or explore calming techniques?",
    ],
    "anxiety": [
        "Anxiety can be challenging. Would you like to try a grounding exercise, or talk more about it?",
        "I hear you’re feeling anxious. Would you like to discuss it further, or hear some ways to calm your mind?",
        "Anxiety can feel consuming. Let’s talk about it, or I can share a breathing technique that might help.",
    ],
    "sadness": [
        "I’m here to listen. Do you want to talk more about what’s making you feel this way, or hear a comforting thought?",
        "Sadness can be hard to deal with. Would you like to share more, or hear some advice on managing sadness?",
        "It’s okay to feel sad sometimes. Do you want to open up about it, or hear a positive perspective?",
    ],
    "anger": [
        "I understand that anger can feel overwhelming. Would you like to talk about what’s causing it, or hear some calming techniques?",
        "It’s okay to feel angry. Would you prefer to discuss it, or hear ways to manage it constructively?",
        "Anger is a natural emotion. Would you like to share more about it, or learn how to channel it positively?",
    ],
    "guilt": [
        "Guilt can be a heavy feeling. Would you like to explore what’s causing it, or hear some ways to cope?",
        "It’s okay to feel guilty sometimes. Would you like to talk it through, or hear some comforting advice?",
        "Guilt often stems from care. Let’s discuss it, or I can offer tips for self-forgiveness.",
    ],
    "happiness": [
        "I’m so glad to hear that! Would you like to share what’s making you happy, or hear something uplifting?",
        "Happiness is wonderful! Do you want to talk more about it, or reflect on what’s bringing you joy?",
        "That’s great to hear! Would you like to share your good news, or hear something inspiring?",
    ],
    "fear": [
        "Fear can be tough to handle. Would you like to talk about what’s causing it, or hear a tip for managing fear?",
        "I understand that fear can be intense. Do you want to discuss it, or learn ways to face it calmly?",
        "It’s okay to feel scared. Would you like to share more, or hear a grounding technique for fear?",
    ],
    "confusion": [
        "Feeling confused can be disorienting. Would you like to talk about what’s on your mind?",
        "It’s okay to feel uncertain sometimes. Let’s discuss it, or I can offer some guidance to clear things up.",
        "Confusion can be a sign of growth. Would you like to explore what’s causing it, or hear a tip for finding clarity?",
    ],
    "hopefulness": [
        "Hope is a wonderful feeling. Would you like to talk about what’s giving you hope?",
        "It’s great to feel hopeful! Let’s reflect on what’s inspiring you, or hear something encouraging.",
        "Hope can be a powerful motivator. Would you like to share what’s making you feel optimistic?",
    ],
    "loneliness": [
        "I’m here for you. Would you like to talk about what’s making you feel lonely, or hear a comforting thought?",
        "Loneliness can be tough. Would you like to explore ways to feel more connected, or just share what’s on your mind?",
        "It’s okay to feel lonely sometimes. Let’s discuss it, or I can offer ideas to feel more supported.",
    ],
    "default": [
        "I'm here to help however I can. You can talk about stress, anxiety, sadness, or any emotion you’re feeling.",
        "Feel free to share anything on your mind. I’m here to listen and support you.",
        "If you’re not sure where to start, you can tell me how you’re feeling or ask for a self-care tip.",
    ],
    "self_care_tip": [
        "Self-care tip: Taking a few deep breaths or a short walk can help clear your mind.",
        "Self-care tip: Journaling about your feelings can provide some clarity and relief.",
        "Self-care tip: Listening to calming music or spending time in nature can help ease your stress.",
        "Self-care tip: Taking a warm bath or practicing mindfulness can bring some peace.",
        "Self-care tip: Set aside 10 minutes today for something you truly enjoy, like reading or drawing.",
    ],
    "validation": [
        "Your feelings are valid, and I’m here for you. Sometimes it helps just to talk things out.",
        "It’s okay to feel this way. I’m here to listen and support you however I can.",
        "You’re doing your best, and that’s enough. I’m here to support you.",
        "Remember, it’s okay to have hard days. I’m here whenever you need to talk.",
        "You’re not alone. I’m here to listen and support you through this.",
    ]
}

"""# Mood classification"""

def classify_mood(user_input):
    sentiment = sia.polarity_scores(user_input)
    mood_keywords = {
        "stress": ["stressed", "overwhelmed", "pressure", "tense", "burnout"],
        "anxiety": ["anxious", "worried", "nervous", "fear", "panic"],
        "sadness": ["sad", "down", "unhappy", "depressed", "lonely"],
        "anger": ["angry", "frustrated", "mad", "annoyed", "rage"],
        "guilt": ["guilty", "regret", "ashamed", "sorry"],
        "happiness": ["happy", "joyful", "excited", "grateful", "content"],
        "fear": ["afraid", "scared", "fearful", "terrified", "frightened"],
        "confusion": ["confused", "lost", "uncertain", "unsure", "doubt"],
        "hopefulness": ["hopeful", "optimistic", "encouraged", "positive", "inspired"],
        "loneliness": ["lonely", "alone", "isolated", "disconnected"]
    }

    for mood, keywords in mood_keywords.items():
        if any(keyword in user_input.lower() for keyword in keywords):
            return mood

    if sentiment["compound"] <= -0.5:
        return "sadness"
    elif sentiment["compound"] >= 0.5:
        return "happiness"
    else:
        return "default"

"""# Option mode"""

def option_mode(mood):
    options = [
        "Hear a self-care tip",
        "Talk more about this",
        "Exit conversation"
    ]

    print("\nPlease choose one of the following options:")
    for i, option in enumerate(options, start=1):
        print(f"{i}. {option}")

    choice = input("Enter the number of your choice: ")

    if choice == "1":
        print(f"Bot: {random.choice(RESPONSE_LIBRARY['self_care_tip'])}")
    elif choice == "2":
        print(f"Bot: {random.choice(RESPONSE_LIBRARY[mood])}")
    elif choice == "3":
        print("Bot: Take care! Remember, I’m here whenever you need to talk.")
        return False
    else:
        print("Bot: I'm here whenever you're ready to share.")
    return True

"""# Chat flow"""

def start_chat():
    print("Hello! I’m here to support you. You can type 'quit' anytime to end the conversation.")

    while True:
        user_input = input("You: ")
        if user_input.lower() in ["quit", "exit", "bye"]:
            print("Bot: Take care! Remember, I’m here whenever you need to talk.")
            break

        mood = classify_mood(user_input)
        response = random.choice(RESPONSE_LIBRARY[mood])
        print(f"Bot: {response}")

        if mood in RESPONSE_LIBRARY and mood != "default":
            while option_mode(mood):
                pass

"""# Run the chatbot"""

if __name__ == "__main__":
    start_chat()

"""# Conversation Example"""

I’ve been feeling very anxious lately.
I feel so lonely these days.
It’s just hard when I don’t have many people to talk to.
I’m also feeling a bit confused about my future.
Yeah, I just don’t know what I want to do.